version: '2'

services:

  broadsea-methods-library:
    image: ohdsi/broadsea-methodslibrary
    ports:
      - "8787:8787"
      - "6311:6311"

  broadsea-webtools:
    image: ohdsi/broadsea-webtools
    ports:
      - "8080:8080"
    volumes:
     - .:/tmp/drivers/:ro
     - .:/tmp/achilles-data-reports/:ro
    environment:
     - WEBAPI_URL=http://192.168.99.100:8080
     - env=webapi-postgresql
     - datasource.driverClassName=org.postgresql.Driver
     - datasource.url=jdbc:postgresql://192.168.99.100:5432/secret-database-name
     - datasource.ohdsi.schema=ohdsi
     - datasource.username=secret-user-name
     - datasource.password=secret-user-password
     - spring.jpa.properties.hibernate.default_schema=ohdsi
     - spring.batch.repository.tableprefix=ohdsi.BATCH_
     - flyway.datasource.driverClassName=org.postgresql.Driver
     - flyway.datasource.url=jdbc:postgresql://192.168.99.100:5432/secret-database-name
     - flyway.schemas=ohdsi
     - flyway.placeholders.ohdsiSchema=ohdsi
     - flyway.datasource.username=secret-user-name
     - flyway.datasource.password=secret-user-password
     - flyway.locations=classpath:db/migration/postgresql
